CREATE TABLE public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  deadline DATE,
  priority TEXT DEFAULT 'Medium'::text,
  category TEXT,
  status TEXT DEFAULT 'Pending'::text NOT NULL
);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tasks"
ON public.tasks FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own tasks"
ON public.tasks FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tasks"
ON public.tasks FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tasks"
ON public.tasks FOR DELETE
USING (auth.uid() = user_id);

COMMENT ON COLUMN public.tasks.name IS 'The title or name of the task.';
COMMENT ON COLUMN public.tasks.priority IS 'Priority level, e.g., High, Medium, Low.';
COMMENT ON COLUMN public.tasks.status IS 'Current status, e.g., Pending, In Progress, Completed.';
